#+TITLE: English Grammar in Use
#+OPTIONS: num:nil toc:nil

* Present
** Present continuous (I am doing)
*** 1
    Am/is/are + -ing
    | I *am*              | driving  |
    | he/she/it *is*      | working  |
    | we/you/they *are*   | doing    |
    |---------------------+----------|
    | I am not            | driving  |
    | he/she/it is not    | working  |
    | we/you/they are not | doing    |
    |---------------------+----------|
    | am I                | driving? |
    | is he/she/it        | working? |
    | are we/you/they     | doing?   |

*** 2
    I am doiong something = I'm in the middle of doing it;
    I've started doing it and I haven't finished.

    /She is driving to work./
    
** Present simple (I do)
*** 1
    | I/we/you/they | drive/work/do     |        |
    | he/she/it     | drives/works/does |        |
    |---------------+-------------------+--------|
    | I/we/you/they | don't             | work   |
    | he/she/it     | doesn't           | drive  |
    |---------------+-------------------+--------|
    | do            | I/we/you/they     | work?  |
    | does          | he/she/it         | drive? |

*** 2
    1. We use the present simple to talk about things in general.

       Whe use it to say that something happens all the time or
       repeatedly, or that something is true in general.

       /He drives a bus./

    2. We use present simple to say how often we do things.

       /He does it every day./

    3. I promise / I apologise

       I advise / I insist / I agree / I refuse/ etc.

       /I promise I won't be late./

** Present continuous and present simple
   1. *I always do* and *I'm always doing*

      I always do (somesing) = I do it every time.
      /I always go to work by car./

      I'm always doing (something) = I do it very often, often than
      normal.

      /I'm always losing things today./

   2. The following verbs are not normally used in the present
      continuous
	  
      Like, want, need, prefer, know, realise, suppose, mean,
      understand, belive, remember, belong, fit, contain, consist, seem

      /I'm hungry. I *want* something to eat./

   3. Think
	  
      When *think* means 'belive', we don't use the continuous.
      /I think she is Canadian, but I'm not sure/

      When *think* means 'consider', the continuous is possible:
      /I'm thinking about what happened./

   4. See hear smell taste

      We normally use the present simple with these verbs.
      /This room *smells*. Let's open a window./

   5. Look feel
	  
      You can use the present simple or continuous to say how somebody
      looks or feels now.
      /You look well today/ or /You are looking well today/

      *But*
      /I usually feel tired in the morning/

   6. *He is selfish* and *He is being selfish*

      He *is being* = He is behaving/ He is acting.
      /I can't understand why he's being so selfish./

      We use *am/is/are being* to say how somebody is *behaving*.

* Past
** Past simple (I did)
*** 1
    In questions and negatives we use did/didn't + infinitive.
*** 2
    1. Regular and irregular verbs.
       Very often the past simple ends in -*ed*
       /lived,started,stopped/
       
       But many verbs are *irregular*.
       /write->wrote,see->saw/

    2. be
       The past of *be(am/is/are)* is was/were.
** Past continuous (I was doing)
*** 1
    Was/were -ing
*** 2
    I *was doing* something = I was in the middle of doing tomething
    at a certain time. The action or situation had alaready started
    before this time, but had not finished.
    
    We often use the past simple and the pastcontinuous together to
    say that somethin happened in the middle of something eles.
    /Matt *phoned* while we *were having* dinner/

    But we use the past simple to say that one thing happened after
    another.
    / I *was walking* along the road when I *saw* Dan./

    Some verbs(for example, *know* and *want*) are not normally used
    in the continouse.
* Present perfect and past
** Present perfect
*** 1
    | I/we/they/you *have*     | finisheed         |
    | he/she/it *has*          | done              |
    |--------------------------+-------------------|
    | I/we/they/you *have not* | /past participle/ |
    | he/she/it *has not*      |                   |
    |--------------------------+-------------------|
    | Have I/...               | /past participle/ |
    | Has she                  |                   |
*** 2
    When we say that 'somethings *has happened*', this is usually new
    information
    /Ow! I've cut my finger./

    When we use the present perfect, there is a connection with
    *now*. The action in the past has a result now.
    /I can't find my bag. Have you seen it?/

    Differences between gone(to) and been(to):
    /He is on holiday. He *has gone to* Italy./ (= he is there now or
    on his way there.)
    /He is back home now. He *has been to* Italy./ (= he has now come
    back.)

    Present perfect with *just*, *already* and *yet*:
    Just = a short time ago
    /I've just arrived./
    Already = something happened sooner than expected
    /She's already left/
    Yet = until now. Yet shows that the speaker is expectign something
    to happen. Use yes only in questions and negative sentences.
    /I've written the email, but I *haven't sent* it *yet*./
*** 3
    When we talk about a period of time that continues from the past
    until now, we use the present perfect.

    Recently/in the last few days/so far/since breakfast
    /Have you heard anything from Brian recently?/

    In the same way we use the present perfect with *today* / *this
    evening* / *this year* when these periods are not finished at the
    time of speaking.
    / I've drunk four cups of coffee today./

    We say: It's the (first) time something has happened
    /It's the first time he has drivend a car./
** Present perfect continuous
*** 1
    Have/has been -ing
    | I/we/they/you have | been | doing   |
    | he/she/it has      | been | playing |
*** 2
   We use the present perfect continuous for an activity that has
   recently stopped or just stopped. There is connection with now:
   /Paul is very tired. He *has been working* very hard./

   We use the present perfect continuous with *how long*, *for* and
   *since*. The activity is still happening or has just stopped.
   /*How long have* you *been learning* English?/

   
   

** Present perfect continuous and simple
*** 1
   - Present perfect continuous

     /She *has been painting* her bedroom./
     We are thinking of the activity. It does not matter whether it
     has been finished or not.

   - Present perfect

     /She *has painted* her bedroom./
     Here, the important thing is that something has been
     finished. *Has painted* is a completed action. We are intrested
     in the result of the activity, not the activity itself.
*** 2
   - Present perfect continuous
     
     We use the continuous to say *how long*
     /How long *have* you been reading that book?/
     
   - Present perfect
     We use the simple to say *how much*, *how many* or *how many
     times*
     /How much of that book *have* you *read*?/
*** 3
    Some verbs (know/like/belive/...) are not normally used in the
    continuous
    /I've known about the problem for a long time./
** How long have you (been)
   We use the present perfect to talk about something taht began in
   the past and still continues now.
   /He has been in hospital since Monday./

   You can use either the present perfect continuous or simple with
   *live* and *work*:
   /Julia *has been living* / *has lived* here for a long time/
   But use the simple(I've lived/I've done) with *always*:
   /I've always lived in the country/

   We say *I haven't done* someshing *since/for*
   /I haven't seen him since Monday/
